url: "https://myxotod.github.io"
baseurl: "/Vertical-Writing-Sandbox"
title: "Vertical Writing Sandbox"
permalink: /:title
livereload: true
sass:
  sass_dir: assets/stylesheets/scss
  style: compressed